"""
report_generator.py
--------------------
Generates a downloadable PDF analysis report using reportlab.
"""

import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)


def generate_pdf_report(analysis_data: dict) -> bytes:
    """
    analysis_data expects keys:
      ats_result, job_match_result (optional), sections, suggestions,
      skill_gap_result (optional), keyword_result (optional)
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                             topMargin=2*cm, bottomMargin=2*cm,
                             leftMargin=2*cm, rightMargin=2*cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleStyle", parent=styles["Title"], fontSize=18, spaceAfter=6)
    heading_style = ParagraphStyle("HeadingStyle", parent=styles["Heading2"], spaceBefore=14, spaceAfter=6)
    normal = styles["Normal"]

    story = []

    story.append(Paragraph("AI Resume Analyzer & Job Matcher", title_style))
    story.append(Paragraph("Resume Analysis Report", styles["Heading3"]))
    story.append(Paragraph(f"Generated on: {datetime.now().strftime('%d %B %Y, %I:%M %p')}", normal))
    story.append(Spacer(1, 12))

    # ATS Score
    ats = analysis_data.get("ats_result")
    if ats:
        story.append(Paragraph("Estimated ATS Compatibility Score", heading_style))
        story.append(Paragraph(
            f"<b>Total Score: {ats['total_score']} / 100</b> — Rating: {ats['rating']}", normal))
        story.append(Spacer(1, 6))

        table_data = [["Component", "Score", "Explanation"]]
        for name, comp in ats["components"].items():
            table_data.append([name, f"{comp['score']} / {comp['max']}", comp["explanation"]])

        t = Table(table_data, colWidths=[5*cm, 2.5*cm, 8*cm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#333333")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(t)

    # Job Match
    job_match = analysis_data.get("job_match_result")
    if job_match:
        story.append(Paragraph("Job Description Match", heading_style))
        story.append(Paragraph(f"Job Match Percentage: <b>{job_match['job_match_percentage']}%</b>", normal))
        story.append(Paragraph(f"Matched Skills: {', '.join(job_match['matched_skills']) or 'None'}", normal))
        story.append(Paragraph(f"Missing Skills: {', '.join(job_match['missing_skills']) or 'None'}", normal))

    # Sections
    sections = analysis_data.get("sections")
    if sections:
        story.append(Paragraph("Detected Resume Sections", heading_style))
        present = [s for s, v in sections.items() if v]
        missing = [s for s, v in sections.items() if not v]
        story.append(Paragraph(f"Present: {', '.join(present) or 'None'}", normal))
        story.append(Paragraph(f"Missing: {', '.join(missing) or 'None'}", normal))

    # Skill Gap
    skill_gap = analysis_data.get("skill_gap_result")
    if skill_gap and skill_gap.get("missing"):
        story.append(Paragraph("Skill Gap Analysis", heading_style))
        for item in skill_gap["missing"]:
            story.append(Paragraph(f"- {item['skill']} ({item['priority']})", normal))

    # Suggestions
    suggestions = analysis_data.get("suggestions")
    if suggestions:
        story.append(Paragraph("Resume Improvement Recommendations", heading_style))
        for s in suggestions:
            story.append(Paragraph(f"- {s}", normal))

    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "Note: This is an estimated ATS compatibility score generated by this project's own "
        "scoring methodology. It does not represent an official score from any commercial ATS vendor.",
        ParagraphStyle("Footer", parent=normal, fontSize=8, textColor=colors.grey)
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
